name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn -B clean test

  deploy:
    name: Deploy para EC2
    runs-on: ubuntu-latest
    needs: test # <- s贸 executa se o job 'test' for bem-sucedido

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v3

      - name: Instalar SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Enviar c贸digo para EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd MySuplementsStore/
            git switch main
            git pull
            sudo docker compose up -d --build
          EOF
